In [1]:
import numpy as np
import time
import pandas as pd

#### We Will Create Different Types of NumPy Array's

In [2]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [9,9,9]
],dtype=np.float32)  ## Specifically Defining the Data Type

b=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
],dtype=np.int32) 

c=np.array([
    [
        [1,2,3,4],
        [1,1,1,1],
        [4,5,6,7],
        [9,8,7,8]
    ]
])

d= np.array( [20,30,40,50] ) ## This Is Not a NumPy array of Inconsistent Shape which can cause problems in multiplications. 
                            ##   Always Remember to Reshape it to (n,1). I have done below

e= np.arange(1,10,2).reshape(1,5) ## ARange Is just a Python Range that Forms a List

f=np.zeros((2,3)) ## A NumPy Array of Zeros. Similarly you Can use np.ones also

g=np.arange(12).reshape(4,3) # To form an array of certain shape from a list of 1D. Remeber Shape when multiplied should 
                             # be equal to n

h=np.eye(8,8,k=1) ## A Diagonal Matrix. K specifies where the diagonal is filled. If 0 it is the center. 

In [3]:
print(a)
print('Shape of a is ', a.shape)
print('Data Type of Elements in a is ',a.dtype)
print('Total Number of ELements In a are ',a.size)
print('***************************')
print(b)
print('Shape of b is ', b.shape)
print('***************************')
print(c)
print('Shape of c is ', c.shape)
print('***************************')
print(d)
print('Shape of d is ', d.shape)
print('***************************')
print(e)
print('Shape of e is ', e.shape)
print('***************************')
print(f)
print('Shape of f is ', f.shape)
print('***************************')
print(g)
print('Shape of g is ', g.shape)
print('***************************')
print(h)
print('Shape of h is ', h.shape)

[[1. 2. 3.]
 [4. 5. 6.]
 [9. 9. 9.]]
Shape of a is  (3, 3)
Data Type of Elements in a is  float32
Total Number of ELements In a are  9
***************************
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of b is  (3, 3)
***************************
[[[1 2 3 4]
  [1 1 1 1]
  [4 5 6 7]
  [9 8 7 8]]]
Shape of c is  (1, 4, 4)
***************************
[20 30 40 50]
Shape of d is  (4,)
***************************
[[1 3 5 7 9]]
Shape of e is  (1, 5)
***************************
[[0. 0. 0.]
 [0. 0. 0.]]
Shape of f is  (2, 3)
***************************
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape of g is  (4, 3)
***************************
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Shape of h is  (8, 8)


In [4]:
b**2

array([[ 100,  400,  900],
       [1600, 2500, 3600],
       [4900, 6400, 8100]], dtype=int32)

####  Why NumPy Array. Here is The Performance Comparison for normal element wise multiplication and Multiplication in a Vectorized way.

This is just a small data so there wont be much difference but when the data size is really huge you will see the impact.

In [5]:
start = time.time()
np.arange(1,100000001).reshape(10000,10000)*np.arange(1,100000001).reshape(10000,10000)
end = time.time()
print(end - start)

0.6920003890991211


### Vectorized Way

In [6]:
start = time.time()
np.multiply(np.arange(1,100000001).reshape(10000,10000),np.arange(1,100000001).reshape(10000,10000))
end = time.time()
print(end - start)

0.6754422187805176


##### Simple Vs NumPy Methods To Perform Different Mathematical Operations.

#### Remember:- Axis=0 means Along The Column and Axis=1 Along the Row

In [7]:
print(a+b)
print('********************************************')
print(np.add(a,b))

[[11. 22. 33.]
 [44. 55. 66.]
 [79. 89. 99.]]
********************************************
[[11. 22. 33.]
 [44. 55. 66.]
 [79. 89. 99.]]


In [8]:
print(a-b)
print('********************************************')
print(np.subtract(a,b))

[[ -9. -18. -27.]
 [-36. -45. -54.]
 [-61. -71. -81.]]
********************************************
[[ -9. -18. -27.]
 [-36. -45. -54.]
 [-61. -71. -81.]]


In [9]:
print(a*b)
print('********************************************')
print(np.multiply(a,b))

[[ 10.  40.  90.]
 [160. 250. 360.]
 [630. 720. 810.]]
********************************************
[[ 10.  40.  90.]
 [160. 250. 360.]
 [630. 720. 810.]]


In [10]:
print(a**b)
print('********************************************')
print(np.power(a,b))

[[1.00000000e+00 1.04857600e+06 2.05891132e+14]
 [1.20892582e+24 8.88178420e+34 4.88736780e+46]
 [6.26578748e+66 2.18474501e+76 7.61773480e+85]]
********************************************
[[1.00000000e+00 1.04857600e+06 2.05891132e+14]
 [1.20892582e+24 8.88178420e+34 4.88736780e+46]
 [6.26578748e+66 2.18474501e+76 7.61773480e+85]]


In [11]:
a<5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [12]:
a.dot(b) ## Matrix Multiplication. This is Not Element Wise.

array([[ 300.,  360.,  420.],
       [ 660.,  810.,  960.],
       [1080., 1350., 1620.]])

In [13]:
print(np.sum(a))
print('********************************************')
print(np.sum(a,axis=0))
print('********************************************')
print(np.sum(a,axis=1))

48.0
********************************************
[14. 16. 18.]
********************************************
[ 6. 15. 27.]


In [14]:
print(np.min(a))
print('********************************************')
print(np.min(a,axis=0))
print('********************************************')
print(np.min(a,axis=1))

1.0
********************************************
[1. 2. 3.]
********************************************
[1. 4. 9.]


In [15]:
print(np.prod(a))
print('********************************************')
print(np.prod(a,axis=0))
print('********************************************')
print(np.prod(a,axis=1))

524880.0
********************************************
[ 36.  90. 162.]
********************************************
[  6. 120. 729.]


In [16]:
np.linalg.svd(a)

(array([[-0.19424398, -0.6989886 , -0.6882472 ],
        [-0.47950166, -0.5444207 ,  0.6882472 ],
        [-0.85577303,  0.46370354, -0.22941573]], dtype=float32),
 array([1.8190639e+01, 1.7608637e+00, 9.6880399e-17], dtype=float32),
 array([[-0.53951967, -0.5765577 , -0.6135957 ],
        [ 0.73637754,  0.03024143, -0.6758947 ],
        [-0.4082483 ,  0.8164966 , -0.4082483 ]], dtype=float32))

In [17]:
print(np.cumsum(a))
print('********************************************')
print(np.cumsum(a,axis=0))
print('********************************************')
print(np.cumsum(a,axis=1))

[ 1.  3.  6. 10. 15. 21. 30. 39. 48.]
********************************************
[[ 1.  2.  3.]
 [ 5.  7.  9.]
 [14. 16. 18.]]
********************************************
[[ 1.  3.  6.]
 [ 4.  9. 15.]
 [ 9. 18. 27.]]


In [18]:
a.cumprod(axis=0) 

array([[  1.,   2.,   3.],
       [  4.,  10.,  18.],
       [ 36.,  90., 162.]], dtype=float32)

In [19]:
np.add(a,b) # We can Add Two arrays also

array([[11., 22., 33.],
       [44., 55., 66.],
       [79., 89., 99.]])

In [20]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [9., 9., 9.]], dtype=float32)

In [21]:
a[0:2] # Indexing to select Desired Rows and Columns

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [22]:
a[1,2] # Row and Column Numbers are seperated by ','

6.0

In [23]:
a[[0,2],:]

array([[1., 2., 3.],
       [9., 9., 9.]], dtype=float32)

In [24]:
a[:,1]

array([2., 5., 9.], dtype=float32)

In [25]:
a[::-1].T # Inverting a 2D Array and Then Transposing It.

array([[9., 4., 1.],
       [9., 5., 2.],
       [9., 6., 3.]], dtype=float32)

In [26]:
a.T

array([[1., 4., 9.],
       [2., 5., 9.],
       [3., 6., 9.]], dtype=float32)

In [27]:
a.flatten()

array([1., 2., 3., 4., 5., 6., 9., 9., 9.], dtype=float32)

In [28]:
a.ravel()

array([1., 2., 3., 4., 5., 6., 9., 9., 9.], dtype=float32)

#### Notice How flatten and Ravel does the same work

In [29]:
c=b-a
len(c[c!=0])  #### Way to Find How many Elements are Different Index Wise

9

In [30]:
np.count_nonzero(np.array([1,2,0,2,1])-np.array([1,0,3,2,1]))  #### Way to Find How many Elements are Different Index Wise

2

In [31]:
np.intersect1d(np.array([1,2,2,3,4,5,6,7,8,9]),np.array([0,2,2,3,4,5,8,9,10]),return_indices=True)

#### Way to Find How many Elements are Different. Remember Here it doesnt take Index Wise.

(array([2, 3, 4, 5, 8, 9]),
 array([1, 3, 4, 5, 8, 9], dtype=int64),
 array([1, 3, 4, 5, 6, 7], dtype=int64))

In [32]:
np.intersect1d(np.array([1,2,2,0,0]),np.array([2,1,1,0,1]),return_indices=True)

(array([0, 1, 2]),
 array([3, 0, 1], dtype=int64),
 array([3, 1, 0], dtype=int64))

In [33]:
np.array([0,2,2,3,4,5,8,9,10])[[1, 3, 4, 5, 6, 7]]

array([2, 3, 4, 5, 8, 9])

#### Stacking Array's Using Different Functions

In [34]:
np.vstack((a,b))

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 9.,  9.,  9.],
       [10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [35]:
np.hstack((a,b))

array([[ 1.,  2.,  3., 10., 20., 30.],
       [ 4.,  5.,  6., 40., 50., 60.],
       [ 9.,  9.,  9., 70., 80., 90.]])

In [36]:
np.concatenate((a,b),axis=0)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 9.,  9.,  9.],
       [10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [37]:
np.concatenate((a,b),axis=1)

array([[ 1.,  2.,  3., 10., 20., 30.],
       [ 4.,  5.,  6., 40., 50., 60.],
       [ 9.,  9.,  9., 70., 80., 90.]])

In [38]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [9., 9., 9.]], dtype=float32)

In [39]:
np.argmax(np.array([[1., 2., 3.],[4., 5., 6.],
       [7., 80., 9.]]))

7

In [40]:
pd.Series([100,2000,1,3]).idxmax()

1

In [41]:
pd.Series(np.array([100,2000,1,3])).idxmax()

1

### Argmax and Argmin  are Very Important Functions and the Same Can be Done With Pandas Series and then Fetch that Index specially in a Pandas dataframe

In [42]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [9., 9., 9.]], dtype=float32)

In [43]:
a>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [44]:
np.bincount(a.astype(int).ravel()==9) ## Counts The Number of Times 9 is Present.

array([6, 3], dtype=int64)

In [45]:
np.nan_to_num(np.array([[1,2,np.nan]])) ## Converting the nan(or Null Values) To an Integer

array([[1., 2., 0.]])

## Broadcasting 

One of the Most Important Topic In NumPy. It works with the below rules.

Two dimensions are compatible when

1. they are equal, or
2. one of them is 1

Read More At :- https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [46]:
np.array([0.0, 10.0, 20.0, 30.0])+ np.array([1.0, 2.0, 3.0]) 

# Here Rule Voilated Because Neither the Dimensions are Same Not Any One of them is 1

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [47]:
np.array([[0.0, 10.0, 20.0, 30.0],[0.0, 10.0, 20.0, 30.0],[0.0, 10.0, 20.0, 30.0]])+ np.array([1.0, 2.0, 3.0,4.0])

# Here the 1st Array is (4,2) and Second is (4,1). So the 2nd Array will be applied to both Rows

array([[ 1., 12., 23., 34.],
       [ 1., 12., 23., 34.],
       [ 1., 12., 23., 34.]])

In [48]:
np.ones((3,4))+np.ones((1,5)) # Here Also Rule is Voilated.

ValueError: operands could not be broadcast together with shapes (3,4) (1,5) 

In [49]:
print(np.ones((3,4)))
print('*****************************')
print(np.ones((1,4)))
print('*****************************')
print(np.ones((4,1)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
*****************************
[[1. 1. 1. 1.]]
*****************************
[[1.]
 [1.]
 [1.]
 [1.]]


In [50]:
np.ones((3,4))+np.ones((1,4)) # See Above and Imagine How the sameller was added to the smaller one

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [51]:
np.ones((4,3))+np.ones((4,1))

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])